FROM quantumobject/docker-zoneminder
LABEL org.freenas.interactive="false"			\
      org.freenas.version="1"				\
      org.freenas.upgradeable="true" 			\
      org.freenas.expose-ports-at-host="true" 		\
      org.freenas.autostart="true" 			\
      org.freenas.volumes="[				\
          {					\
              \"name\": \"/zoneminder\",			\
              \"descr\": \"Config storage space\"		\
          }					\
      ]" 						\
      