FROM timhaak/plex:latest
LABEL org.freenas.interactive="false" \
      org.freenas.upgradeable="true" \
      org.freenas.expose_ports_at_host="true" \
      org.freenas.autostart="true" \
      org.freenas.port_mappings="1900:1900/udp,32469:32469/udp,5353:5353/udp,32400:32400/tcp,32469:32469/tcp"

