FROM nginx:latest
LABEL org.freenas.interactive="false"
LABEL org.freenas.upgradeable="false"
LABEL org.freenas.expose_ports_at_host="true"
LABEL org.freenas.autostart="true"
LABEL org.freenas.port_mappings="80:8080/tcp"

