FROM nginx:latest
LABEL org.freenas.interactive="false" \
      org.freenas.upgradeable="false" \
      org.freenas.expose_ports_at_host="true" \
      org.freenas.autostart="true" \
      org.freenas.port_mappings="80:8080/tcp"

